### PR TITLE
Fix translators

### PR DESCRIPTION
**Pull request by DaMatrix**
**This is still WIP, do not merge**
I'm working on fixing the translators. Yeah. What do I say?

### CODE REVIEW

**Comment by DaMatrix** [comment]
I'm going to need to figure out what DataCache is, as it seems to have been removed from the code.

**Comment by robotman3000** [comment]
Look at the code in 527b13245f10c20842fedd98c1a2ef41a1f1e4c1. Off the top of my head that is the last commit where the data cache system was still working. Look in UpstreamSeasion. I was planning to reimplement the system in ClientConnection if you want to do it yourself.

**Comment by robotman3000** [comment]
Awesome work, thanks for your help. Have you done anything with chunk translation yet?

**Comment by DaMatrix** [comment]
I haven't started the chunk translator yet, I'm just going through the translators in the order they show up in my IDE.

**Comment by DaMatrix** [comment]
Well, I've got all the PC translators to compile.

**Comment by DaMatrix** [comment]
OK. All the translators compile now, but there's lots of errors in the log when trying to connect. Working on that now

**Comment by DaMatrix** [comment]
Hm. I'm kinda stuck here, if somebody who actually understands the MCPE protocol could give me a hand here, it would be greatly appreciated. Here's what I get when connecting to a server from MCPE:
http://pastebin.com/EQhXCSYT
I don't understand how there could be any ArrayIndexOutOfBoundsExceptions here...

**Comment by DaMatrix** [comment]
I've solved all the exceptions, everything should work now, but it doesn't. The client waits a moment with a blank screen and then says "Disconnected from server". I don't understand the MCPE protocol in the slightest, so I can't really do much here. :/

**Comment by robotman3000** [comment]
We might want to get MrPowerGamerBR in on this.

**Comment by robotman3000** [comment]
@MrPowerGamerBR Would you be able to help with fixing the translators? I remember you had wanted to do that before the new network system was implemented.

**Comment by robotman3000** [comment]
@DaMatrix I do know that at least the chunk translator isn't translating properly because of the chunk format change. See issue [#5](https://github.com/robotman3000/DragonProxy/issues/5) in my fork.

**Comment by MrPowerGamerBR** [comment]
@robotman3000 sorry, I'm busy with my upcoming MCPE server. :/

(I actually wanted DragonProxy to use a PC server for my upcoming MCPE server, but since I got stuck in the chunk translator issue, I started poking the Nukkit source to see if I could understand something... then I said fuck it and forked Nukkit)

**Comment by robotman3000** [comment]
@MrPowerGamerBR Ok, Thanks anyway.

However you may be interested to know that the packets I was sending in mimimalClientHandshake may have had an affect on whether the chunks would render or not. PE -> PE packet passthrough worked except for chunk's until I stopped using minimalClientHandshake, at which point they just started appearing like normal.

**Comment by MrPowerGamerBR** [comment]
@robotman3000 strange... so PE -> PE passthrough does work then? Maybe I will take a look later then.

The problem for me is the chunk packet, because I can't figure out why that doesn't work.

**Comment by robotman3000** [comment]
@MrPowerGamerBR Yes it works.

**Comment by robotman3000** [comment]
@MrPowerGamerBR I also had to change the RakNet packet reliability to unreliable, in addition to not using minimalClientHandshake. That is about the extent of my knowledge about this problem that you don't already know

**Comment by MrPowerGamerBR** [comment]
@robotman3000 as far as I know MCPE uses RakNet reliable ordered, strange that it is causing issues with that.

**Comment by robotman3000** [comment]
@MrPowerGamerBR I forget whether it was the client or server protocol adapter I changed to make it work, but I think it was MCPEServerProtocolAdapter

**Comment by MrPowerGamerBR** [comment]
@robotman3000

**Comment by robotman3000** [comment]
@MrPowerGamerBR What server software are you using? It looks like you have a win10 client from the mouse cursor.

**Comment by robotman3000** [comment]
@DragonetMC Are any of you guys available to help with updating the translators?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 yes, MCW10 trying to connect to DragonProxy to a 1.11.2 server (to see what happens to fix the issues)

**Comment by robotman3000** [comment]
@MrPowerGamerBR Does the proxy or the server generate the full server message?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 the client doesn't even connect to the server


I forgot what causes the client to show "The server is full!". 

Nothing in the 1.11.2 server.

(Maybe it is the protocol version? I'm testing with 1.0.3)

**Comment by robotman3000** [comment]
@MrPowerGamerBR This may be worth checking. If the max number of clients is set to -1 in the proxy config file it will refuse all connections. It's a bug that i haven't yet bothered to fix. Basically -1 (MaxOnline) < 0 (CurrentOnline) so the server is full.

**Comment by robotman3000** [comment]
@MrPowerGamerBR Also if that is your problem, I gather that you have a new config file, so set the authentication mode to offline (from cls which is the default). That's the only one that works right now.

**Comment by robotman3000** [comment]
@MrPowerGamerBR If the protocol version were a problem your disconnect message would be different

**Comment by robotman3000** [comment]
@MrPowerGamerBR It would be something about an outdated client or server

**Comment by MrPowerGamerBR** [comment]
@robotman3000 okay, the max player was the issue, but now...

**Comment by MrPowerGamerBR** [comment]
Also I'm compiling with the latest version here, not @DaMatrix's fork.

**Comment by robotman3000** [comment]
@MrPowerGamerBR Which latest version, my fork or the refactor branch?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 your fork

**Comment by robotman3000** [comment]
@MrPowerGamerBR Is that exception keeping you from connecting now?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 yep

**Comment by robotman3000** [comment]
@MrPowerGamerBR Also what issues are you referring to in particular?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 NullPointerException when trying to join the proxy.

I will probably take a look on what is causing this issue later. Also, I'm using "offline" mode in DragonProxy's config.

**Comment by DaMatrix** [comment]
Yeah, as I said I don't get any RuntimeExceptions on my end, it looks like it's running fine but the client doesn't even get to the "Building terrain" screen.

**Comment by robotman3000** [comment]
@MrPowerGamerBR Something to try is using 7e9ed9e7401262a9d1f9b76dece890a49c564704 it's a few commits before the latest one. It is right before the negative-array-size fix which I haven't yet been able to test. The commit I've referenced is the last time I knew both passthrough modes to be working. All packet translation is broken though (The translators won't compile and have to be removed)

**Comment by robotman3000** [comment]
@DaMatrix Are you using a passthrough mode or a translator mode?

**Comment by DaMatrix** [comment]
I'm talking about the translators (because that's what this PR is about)

**Comment by robotman3000** [comment]
@DaMatrix Is minimalClientHandshake enabled. The purpose of that code was to get the client to allow access to the chat by spawning it into the world, which would get you past the loading screens.

**Comment by MrPowerGamerBR** [comment]
And I'm trying to get the proxy working to fix the translators. (Probably I will compile @DaMatrix's fork to see what happens)

@DaMatrix: If you don't send the: PlayStatusPacket, ResourcePackInfoPacket, StartGamePacket and PlayStatusPacket (in this order) you wouldn't get past the "building terrain" screen

**Comment by robotman3000** [comment]
@DaMatrix Yes, MrPowerGamerBR said it better than I did. Look at my comments in the code about those packets for a little more about this

**Comment by robotman3000** [comment]
@DaMatrix I just checked and in MCPEClientProtocolAdapter minimalClientHandshake is never called

**Comment by DaMatrix** [comment]
Does it need to be? I've got this:
https://github.com/2pocket2edition/2p2eProxy/blob/fix/translators/DragonProxy/src/main/java/org/dragonet/proxy/network/translator/pc/PCJoinGamePacketTranslator.java#L84

**Comment by robotman3000** [comment]
That fixes the connection exceptions, but it still doesn't seem to work

**Comment by DaMatrix** [comment]
That's why I'm confused :/

**Comment by DaMatrix** [comment]
Also vaguely on topic: how are you pushing commits to my branch???

**Comment by robotman3000** [comment]
The arrayIndex error was caused by onClientLoginRequest sending the login packet and not the status packet. Look at line 290 in MCPEClientProtocolAdapter

**Comment by robotman3000** [comment]
@DaMatrix Uhh, I have absolutely no idea.

**Comment by robotman3000** [comment]
@DaMatrix Perhaps I have push permissions since your branch is currently in a pull request to mine?

**Comment by DaMatrix** [comment]
Possibly, anyway. I'll test joining again with your commit and see if it helps anything. I wasn't getting any IndexOutOfBoundsExceptions after 8d6f8cafb7830c8c2c59e4d65e1b3d81b8879664 though...

**Comment by DaMatrix** [comment]
Nope, nothing changed. The client still sits there with the dirt background doing nothing while the console spits out stuff about chat packets and such. But shouldn't https://github.com/2pocket2edition/2p2eProxy/blob/fix/translators/DragonProxy/src/main/java/org/dragonet/proxy/network/translator/pc/PCJoinGamePacketTranslator.java#L84 be the same as `minimalClientHandshake()`?

**Comment by robotman3000** [comment]
@MrPowerGamerBR Your problem with my fork is the same I just fixed here because my fork was using minimalClientHandshake. @DaMatrix You weren't having any problem because minimalClientHandshake wasn't being used until I changed it just now.

**Comment by robotman3000** [comment]
@DaMatrix Yes, it should

**Comment by robotman3000** [comment]
@DaMatrix Where do you send a PlayStatus.OK? That is required before the client will do anything else

**Comment by DaMatrix** [comment]
Ah, that could be the problem. That's not sent until `PCLoginSucessPacketTranslator` :/

**Comment by robotman3000** [comment]
@DaMatrix According to http://wiki.vg/Protocol_FAQ LoginSuccess is sent before JoinGame

**Comment by robotman3000** [comment]
@DaMatrix What packets and in what order does the server send data?

**Comment by DaMatrix** [comment]
Then it should have worked initially :/

**Comment by robotman3000** [comment]
Your PC server is set to offline mode right?

**Comment by DaMatrix** [comment]
Well, as of the latest commit it's like this:
PlayStatus.OK -> Client
StartGamePacket
SetEntityData
Respawn
SetSpawnPosition
PlayStatus.SPAWNED

**Comment by DaMatrix** [comment]
Yup, I'm trying to connect to `play.extremecraft.net` (a random offline mode server i found on the interwebs)

**Comment by robotman3000** [comment]
What version MCPE client are you using?

**Comment by DaMatrix** [comment]
1.0.0

**Comment by robotman3000** [comment]
How do you still have 1.0.0? Mine auto updated to 1.0.3

**Comment by robotman3000** [comment]
I'm on win10 though

**Comment by DaMatrix** [comment]
I'm using mcpelauncher-linux, and I still have 1.0.0 on my phone too (I turned google play autoupdates off)

**Comment by DaMatrix** [comment]
I could update to 1.0.3, but I don't think that would help anything. Would it?

**Comment by robotman3000** [comment]
IDK, I am out of time to work on this right now but the LoginSuccess packet doesn't appear to be getting translated on my end

`[11:39:44] [INFO] Sent packet to server: org.spacehq.mc.protocol.packet.handshake.client.HandshakePacket
[11:39:44] [INFO] Sent packet to server: org.spacehq.mc.protocol.packet.login.client.LoginStartPacket
[11:39:44] [INFO] Received packet from server: org.spacehq.mc.protocol.packet.login.server.LoginSetCompressionPacket
[11:39:44] [INFO] Received packet from server: org.spacehq.mc.protocol.packet.login.server.LoginSuccessPacket
[11:39:44] [INFO] Received packet from server: org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket
Server Handling Packet: org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket
[11:39:44] [INFO] >>> org.spacehq.mc.protocol.packet.ingame.server.ServerJoinGamePacket`

**Comment by DaMatrix** [comment]
Should be fixed now, but still not working :/

**Comment by robotman3000** [comment]
Well, now the client will connect to a PC server and spawn into the world without the assistance of minimalClientHandshake. So, that's some progress

**Comment by robotman3000** [comment]
At this point I think we should focus our efforts on updating the chunk translator, because without a world to interact with we can't test most of the other translators. Also the chat packets coming from the client need to be translated.

**Comment by DaMatrix** [comment]
What do we do about commands? PC doesn't send anything similar to an AvalibleCommandsPacket, so although we could simply spam the server with tab completion packets to find out, server owners might hate us lol

**Comment by DaMatrix** [comment]
Chat server to client works, but the client can't seem to send chat BACK. Kinda important.

**Comment by robotman3000** [comment]
@DaMatrix For the problem with commands there are two solutions I can think of that don't involve spamming tab complete packets
First:
We can add some sort of commands.yml type of thing where we give the list of commands and all required information

Second:
This, I think, is the better solution for server software that supports it. We can create a plugin that uses the Bukkit API to send plugin message packets that contain information about the commands available on the server when the proxy connects to the remote server. After all the plugin message system was added with the modding community in mind (At least I'm fairly certain about that)
So the exchange would go something like this:
Proxy sends `PluginMessage` on channel `DragonProxy` with message `requestAvalibleCommands`
Server responds with `PluginMessage` on channel `DragonProxy` with the available commands. Perhaps the command list is in json or yml format. The format could be identical to the format used with the first solution

We may actually want to put both solutions in place to support as many server software's as possible

**Comment by robotman3000** [comment]
@DaMatrix As for the chat issue I have done a minimal amount of investigation. 

Firstly, the client loves to send us BatchPacket's instead of sending them individually, so we will need to implement support for decoding BatchPacket's in the translator system. Write a PEBatchPacketTranslator class and have it call ClientConnection.get(Upstream/Downstream)Protocol().handlePacket(); for every packet contained in the batch packet. The handlePacket method is intended to be the place where all handling of packets from the network side belonging to that ProtocolAdapter should occur. Basically handlePacket is for packet's in and sendPacket is for packet's out

Now all this about BatchPacket's to say, most likely the missing chat packets are in the BatchPackets.

Second: There are a variety of chat packet classes nested inside the sul Text packet. We will need to write a translator for each of them since they don't extend or implement a common chat class.

**Comment by robotman3000** [comment]
@DaMatrix I'll let you be the one to close this PR and resubmit the new one at DragonetMC

**Comment by DaMatrix** [comment]
Ok, will do.

**Comment by DaMatrix** [comment]
https://github.com/DragonetMC/DragonProxy/pull/38

**Pull request closed without merging**
